import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123cls');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Time' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Timesheets' }).locator('i').click();
  await page.getByRole('menuitem', { name: 'Employee Timesheets' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('Orange Test');
  await page.getByRole('option', { name: 'Orange Test' }).click();
  await page.locator('form').getByRole('button', { name: 'View' }).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('Apache Software Foundation');
  await page.getByText('Apache Software Foundation -').click();
  await page.locator('.oxd-icon.bi-caret-down-fill.oxd-select-text--arrow').click();
  await page.getByRole('option', { name: 'Bug Fixes' }).click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('8');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('8');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('8');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('8');
  await page.locator('td:nth-child(7) > .oxd-input-group > div:nth-child(2) > .oxd-input').click();
  await page.locator('.oxd-input.oxd-input--focus').fill('8');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
});